language: go
sudo: false

env:
  - NODE_VERSION="8"

branches:
  only:
    - develop

cache:
  directories:
    - node_modules

before_install:
  - nvm install $NODE_VERSION
  - go get github.com/googlecodelabs/tools/claat

install:
  - npm install

script:
  - cd codelabs; claat export *.md
  - npm run dist
  - unlink dist/codelabs
  - cp -r codelabs dist/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: master
  on:
    branch: develop
